[project]
name = "serve-examples"
version = "0.1.0"
description = ""
authors = [
    {name = "TensorRT LLM [svc_tensorrt_llm@nvidia.com]"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "genai-perf (>=0.0.16,<0.0.17)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
