[project]
name = "tensorrt-llm"
version = "0.1.0"
description = ""
authors = [
    {name = "TensorRT LLM [svc_tensorrt_llm@nvidia.com]"}
]
license = {text = "Apache-2.0"}
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "build (>=1.3.0,<2.0.0)",
    "colored (>=2.3.1,<3.0.0)",
    "cuda-python (>=12,<13)",
    "diffusers (>=0.27.0)",
    "lark (>=1.2.2,<2.0.0)",
    "mpi4py (>=4.1.0,<5.0.0)",
    "numpy (<2)",
    "onnx (>=1.18.0)",
    "onnx-graphsurgeon (>=0.5.2)",
    "openai (>=1.101.0,<2.0.0)",
    "polygraphy (>=0.49.26,<0.50.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "nvidia-ml-py (>=12,<13)",
    "pynvml (==12.0.0)",
    "pulp (>=3.2.2,<4.0.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "h5py (==3.12.1)",
    "strenum (>=0.4.15,<0.5.0)",
    "sentencepiece (>=0.1.99)",
    "tensorrt (>=10.11.0,<10.12.0)",
    "nvidia-nccl-cu12 (>=2.27.7,<3.0.0)",
    "nvidia-cuda-nvrtc-cu12 (>=12.9.86,<13.0.0)",
    "transformers (==4.53.1)",
    "pydantic (>=2.9.1)",
    "pydantic-settings[yaml] (>=2.10.1,<3.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "pillow (==10.3.0)",
    "wheel (<=0.45.1)",
    "datasets (==3.1.0)",
    "evaluate (>=0.4.5,<0.5.0)",
    "mpmath (>=1.3.0)",
    "click (>=8.2.1,<9.0.0)",
    "click-option-group (>=0.5.7,<0.6.0)",
    "aenum (>=3.1.16,<4.0.0)",
    "pyzmq (>=27.0.2,<28.0.0)",
    "fastapi (==0.115.4)",
    "uvicorn (>=0.35.0,<0.36.0)",
    "setuptools (<80)",
    "ordered-set (>=4.1.0,<5.0.0)",
    "einops (>=0.8.1,<0.9.0)",
    "backoff (>=2.2.1,<3.0.0)",
    "nvtx (>=0.2.13,<0.3.0)",
    "meson (>=1.9.0,<2.0.0)",
    "ninja (>=1.13.0,<2.0.0)",
    "etcd3 (>=0.12.0,<0.13.0)",
    "blake3 (>=1.0.5,<2.0.0)",
    "llguidance (==0.7.29)",
    "soundfile (>=0.13.1,<0.14.0)",
    "triton (==3.3.1)",
    "tiktoken (>=0.11.0,<0.12.0)",
    "blobfile (>=3.0.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
